version: '3.8'

services:
  app:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build: .
    container_name: interactive_scraper_app
    ports:
      - "9090:8080"
    depends_on:
      postgres:
        condition: service_healthy
      tor:
        condition: service_started
    
    env_file:
      - .env

    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - TOR_PROXY=socks5://tor:9050

    networks:
      - cti_net
    volumes:
      - ./mitre_rules.json:/app/mitre_rules.json
      - ./targets.yaml:/app/targets.yaml

  postgres:
    container_name: darkweb_postgres
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
    
    networks:
      - cti_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./init-admin.sql:/docker-entrypoint-initdb.d/02-init-admin.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  tor:
    container_name: darkweb_tor
    image: osminogin/tor-simple
    ports:
      - "9050:9050"
    networks:
      - cti_net
    restart: always

networks:
  cti_net:
    driver: bridge

volumes:
  postgres_data: