version: '3.8'

services:
  
  tor:
    image: osminogin/tor-simple
    container_name: darkweb_tor
    ports:
      - "9050:9050" 
    networks:
      - cti_net
    restart: always


  db:
    image: postgres:15-alpine
    container_name: darkweb_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=darkweb_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./init-admin.sql:/docker-entrypoint-initdb.d/02-init-admin.sql
    networks:
      - cti_net
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: . 
    container_name: interactive_scraper_app
    ports:
      - "8080:8080" # 
    environment:
      # Important: we write host=db. Because in docker-compose, the service name acts as the hostname.
      - DB_SOURCE=host=db port=5432 user=postgres password=postgres dbname=darkweb_db sslmode=disable
      - TOR_PROXY=socks5://tor:9050
    depends_on:
      db:
        condition: service_healthy # 
      tor : 
        condition: service_started
    networks:
      - cti_net

  

volumes:
  postgres_data:

networks:
  cti_net: